apiVersion: apps/v1
kind: Deployment
metadata:
  name: listenarr
  labels:
    app.kubernetes.io/name: listenarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: listenarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: listenarr
    spec:
      serviceAccountName: listenarr
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: listenarr
        image: linuxserver/readarr:amd64-nightly@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
        ports:
        - name: http
          containerPort: 8787
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "501"
        - name: PGID
          value: "20"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: data
          mountPath: /config
          subPath: config
        - name: media
          mountPath: /books
          subPath: eBooks
        - name: sabnzbd-downloads
          mountPath: /downloads
          subPath: downloads
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: listenarr-claim
      - name: media
        persistentVolumeClaim:
          claimName: media-claim
      - name: sabnzbd-downloads
        persistentVolumeClaim:
          claimName: sabnzbd-data-claim

