apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
  namespace: kube-system
spec:
  nodeSelector:
    matchExpressions:
    - key: l2.cilium.io/disable
      operator: DoesNotExist
  interfaces:
  - '^enp89s[0-9]+'
  loadBalancerIPs: true
  externalIPs: true

