global:
  namespace: vault
server:
  dataStorage:
    storageClass: vault-data
csi:
  # Settings for the daemonSet used to run the provider.
  daemonSet:
    providersDir: "/etc/kubernetes/secrets-store-csi-providers"
