apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audiobookshelf
  - calibre
  - calibre-web-automated
  - homepage
  - linkding
  - plex
  - prowlarr
  - radarr
  - rustdesk
  - sabnzbd
  - seerr
  - sonarr
  - tautulli
  - unifi
  - uptime-kuma

