apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-stack
  - traefik
  - cert-manager
  - csi-driver-smb
  - cilium
  - vault
  - external-secrets
  - longhorn
  # - renovate

