apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - ../../base/longhorn

configMapGenerator:
- name: longhorn-values
  behavior: replace
  files:
  - values.yaml

patches:
- target:
    kind: HelmRelease
    name: longhorn
  patch: |-
    - op: replace
      path: /spec/chart/spec/version
      value: 1.11.0
