persistence:
  defaultClassReplicaCount: 1
  removeSnapshotsDuringFilesystemTrim: ignored
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
defaultSettings:
  defaultReplicaCount: 1
  disableRevisionCounter: "true"
defaultBackupStore:
  backupTarget: cifs://nas.cruznet.io/Media/Backups/Longhorn
  backupTargetCredentialSecret: cifs-secret
