apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  labels:
    app.kubernetes.io/name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: audiobookshelf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: audiobookshelf
    spec:
      serviceAccountName: audiobookshelf
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # hostNetwork: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.32.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: config
        - name: media
          mountPath: /audiobooks
          subPath: Audiobooks
        - name: media
          mountPath: /podcasts
          subPath: Podcasts
        - name: media
          mountPath: /metadata
          subPath: Audiobookshelf/Metadata
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: audiobookshelf-config-claim
      - name: media
        persistentVolumeClaim:
          claimName: media-claim

