apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`audiobookshelf.cruznet.io`)
    kind: Rule
    services:
    - name: audiobookshelf-ui
      kind: Service
      port: 80
  - match: Host(`abs.cruznet.io`)
    kind: Rule
    services:
    - name: audiobookshelf-ui
      kind: Service
      port: 80
  tls:
    secretName: audiobookshelf-cert

