apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      serviceAccountName: sonarr
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:4.0.16.2944-ls303
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8989
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "501"
        - name: PGID
          value: "20"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: data
          mountPath: /config
          subPath: config
        - name: media
          mountPath: /tv
          subPath: TV
        - name: media
          mountPath: /movies
          subPath: Movies
        - name: sabnzbd-downloads
          mountPath: /downloads
          subPath: downloads
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sonarr-claim
      - name: media
        persistentVolumeClaim:
          claimName: media-claim
      - name: sabnzbd-downloads
        persistentVolumeClaim:
          claimName: sabnzbd-data-claim

