apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - traefik
  - cert-manager
  - csi-driver-smb
  - longhorn
  - metrics-server
  - prometheus-stack
  - external-secrets
  - vault

