apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      serviceAccountName: radarr
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:6.0.4.10291-ls293@sha256:6d3e68474ea146f995af98d3fb2cb1a14e2e4457ddaf035aa5426889e2f9249c
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 7878
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "501"
        - name: PGID
          value: "20"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: data
          mountPath: /config
          subPath: config
        - name: media
          mountPath: /tv
          subPath: TV
        - name: media
          mountPath: /movies
          subPath: Movies
        - name: sabnzbd-downloads
          mountPath: /downloads
          subPath: downloads
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: radarr-claim
      - name: media
        persistentVolumeClaim:
          claimName: media-claim
      - name: sabnzbd-downloads
        persistentVolumeClaim:
          claimName: sabnzbd-data-claim

