apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    app.kubernetes.io/name: seerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seerr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seerr
    spec:
      serviceAccountName: seerr
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: seerr
        image: ghcr.io/seerr-team/seerr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5055
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: data
          mountPath: /app/config
          subPath: config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: seerr-claim

