apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr
  namespace: seerr
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`seerr.cruznet.io`)
    kind: Rule
    services:
    - name: seerr
      kind: Service
      port: 5055
  - match: Host(`overseerr.cruznet.io`)
    kind: Rule
    services:
    - name: seerr
      kind: Service
      port: 5055
  tls:
    secretName: seerr-cert

