apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - helm-release.yaml
  - helm-repository.yaml
  - ingress.yaml
  - namespace.yaml
  - secret.yaml
  - service-account.yaml
  - storage.yaml

configMapGenerator:
- name: seerr-values
  files:
  - values.yaml

configurations:
- kustomize-config.yaml

