apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  labels:
    app.kubernetes.io/name: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unifi
    spec:
      serviceAccountName: unifi
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: unifi
        image: jacobalberty/unifi:v10.0.162@sha256:896c0ab82d33300694dae82982fd7094497afcbea0be92cadc1e94bfead731d3
        imagePullPolicy: IfNotPresent
        ports:
        - name: webui
          containerPort: 8443
          protocol: TCP
        - name: communication
          containerPort: 8080
          protocol: TCP
        - name: stun
          containerPort: 3478
          protocol: UDP
        - name: discovery
          containerPort: 10001
          protocol: UDP
        - name: syslog
          containerPort: 5514
          protocol: UDP
        - name: speed-test
          containerPort: 6789
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "501"
        - name: PGID
          value: "20"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: data
          mountPath: /unifi
          subPath: config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: unifi-claim

