apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: calibre-web-automated
  namespace: calibre-web-automated
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`calibre-web-automated.cruznet.io`)
    kind: Rule
    services:
    - name: calibre-web-automated
      kind: Service
      port: 8083
  - match: Host(`cwa.cruznet.io`)
    kind: Rule
    services:
    - name: calibre-web-automated
      kind: Service
      port: 8083
  tls:
    secretName: calibre-web-automated-cert

