apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    app.kubernetes.io/name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
    spec:
      serviceAccountName: plex
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # hostNetwork: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:1.43.0.10492-121068a07-ls294@sha256:55c2def2eb662c2ce1a13e569278aeb87b2509ac7c57711d0da0a5d6d1607ad8
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 32400
          protocol: TCP
        - name: dlna
          containerPort: 1900
          protocol: UDP
        - name: bonjour
          containerPort: 5353
          protocol: UDP
        - name: companion
          containerPort: 8324
          protocol: TCP
        - name: gdm
          containerPort: 32410
          protocol: UDP
        - name: gdm2
          containerPort: 32412
          protocol: UDP
        - name: gdm3
          containerPort: 32413
          protocol: UDP
        - name: gdm4
          containerPort: 32414
          protocol: UDP
        - name: dlna2
          containerPort: 32469
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        - name: ADVERTISE_IP
          value: "http://172.31.1.249:32400"
        - name: ALLOWED_NETWORKS
          value: "172.31.1.0/24"
        - name: VERSION
          value: "docker"
        - name: PLEX_CLAIM
          value: "claim-WFo4N1H3UPtVhCCvqc_2"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: config
        - name: transcode
          mountPath: /transcode
        - name: quicksync
          mountPath: /dev/dri
        - name: media
          mountPath: /tv
          subPath: TV
        - name: media
          mountPath: /movies
          subPath: Movies
        - name: media
          mountPath: /audiobooks
          subPath: Audiobooks
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config-claim
      - name: transcode
        persistentVolumeClaim:
          claimName: plex-transcode-claim
      - hostPath:
          path: /dev/dri
          type: ""
        name: quicksync
      - name: media
        persistentVolumeClaim:
          claimName: media-claim

