global:
  rbac:
    pspEnabled: false
    pspAnnotations: {}
alertmanager:
  podDisruptionBudget:
    maxUnavailable: ""
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alert-manager-claim
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
          selector:
            matchLabels:
              app: alert-manager
grafana:
  defaultDashboardsTimezone: America/Los_Angeles
  adminPassword: prom-operator
  persistence:
    enabled: true
    type: sts
    storageClassName: grafana-data
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
kube-state-metrics:
  namespaceOverride: ""
  rbac:
    create: true
  prometheus:
    monitor:
      interval: ""
      sampleLimit: 0
      targetLimit: 0
      labelLimit: 0
      labelNameLengthLimit: 0
      labelValueLengthLimit: 0
      scrapeTimeout: ""
      proxyUrl: ""
      honorLabels: true
      metricRelabelings: []
      relabelings: []
  selfMonitor:
    enabled: false
prometheus-node-exporter:
  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
prometheusOperator:
  admissionWebhooks:
    deployment:
      podDisruptionBudget:
        maxUnavailable: ""
  podDisruptionBudget:
    maxUnavailable: ""
prometheus:
  thanosServiceMonitor:
    scrapeProtocols: []
  podDisruptionBudget:
    maxUnavailable: ""
  podSecurityPolicy:
    allowedCapabilities: []
    allowedHostPaths: []
    volumes: []
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-claim
        spec:
          storageClassName: ""
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              # storage: 50Gi
              storage: 10Gi
          selector:
            matchLabels:
              app: prometheus
thanosRuler:
  podDisruptionBudget:
    maxUnavailable: ""
