apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk
  labels:
    app.kubernetes.io/name: rustdesk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rustdesk
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustdesk
    spec:
      serviceAccountName: rustdesk
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      containers:
      - name: hbbr
        args:
        - hbbr
        image: rustdesk/rustdesk-server:1.1.15@sha256:10818ec05b179039c6660f4d8e74b303f0db2858bbad2b18e24992ea22d54cd6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 21117
          - containerPort: 21119
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: hbbr
          mountPath: /root
          subPath: config
      - name: hbbs
        args:
        - hbbs
        - -r
        - localhost:21117
        image: rustdesk/rustdesk-server:1.1.15@sha256:10818ec05b179039c6660f4d8e74b303f0db2858bbad2b18e24992ea22d54cd6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 21115
          - containerPort: 21116
          - containerPort: 21116
            protocol: UDP
          - containerPort: 21118
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: hbbs
          mountPath: /root
          subPath: config
      volumes:
      - name: hbbr
        persistentVolumeClaim:
          claimName: hbbr-claim
      - name: hbbs
        persistentVolumeClaim:
          claimName: hbbs-claim

